# Generated by Django 5.2.1 on 2025-05-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular User'), ('organization', 'Organization')], default='regular', help_text='Designates the type of user.', max_length=20),
        ),
    ]
