# Generated by Django 5.2.1 on 2025-05-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeLoveEvents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
