# Generated by Django 5.2.1 on 2025-05-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeLoveEvents', '0002_alter_event_date_end_alter_event_date_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ManyToManyField(related_name='events', to='WeLoveEvents.organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='favourite',
            field=models.ManyToManyField(related_name='favourite_events', to='WeLoveEvents.user'),
        ),
    ]
