# Generated by Django 5.2.1 on 2025-05-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeLoveEvents', '0003_organization_user_alter_event_id_event_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
