# Generated by Django 5.2.1 on 2025-05-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeLoveEvents', '0004_organization_logo_alter_organization_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='favourite',
        ),
        migrations.AddField(
            model_name='user',
            name='favourite',
            field=models.ManyToManyField(related_name='favourite_events', to='WeLoveEvents.event'),
        ),
    ]
