# Generated by Django 5.2.1 on 2025-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeLoveEvents', '0005_remove_event_favourite_user_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite_events', to='WeLoveEvents.event'),
        ),
    ]
