# Generated by Django 5.2.1 on 2025-05-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeLoveEvents', '0006_alter_user_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to=''),
        ),
    ]
